create extension if not exists "pgcrypto";

create type post_status as enum ('draft', 'published');

create table if not exists posts (
  id uuid primary key default gen_random_uuid(),
  author_id uuid references auth.users not null,
  title text not null,
  slug text not null unique,
  tags text[] not null default '{}',
  excerpt text,
  content text not null,
  cover_image_url text,
  reading_time_minutes int,
  meta_title text,
  meta_description text,
  status post_status not null default 'draft',
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists post_views (
  id bigint generated by default as identity primary key,
  post_id uuid references posts(id) on delete cascade not null,
  viewer_hash text not null,
  created_at timestamptz not null default now()
);

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_posts_updated_at
before update on posts
for each row
execute function set_updated_at();

create index if not exists posts_status_published_at_idx on posts (status, published_at);
create index if not exists posts_author_id_idx on posts (author_id);
create index if not exists post_views_post_id_idx on post_views (post_id);
create index if not exists post_views_viewer_hash_idx on post_views (viewer_hash);

create view post_view_counts as
select
  post_id,
  count(*)::int as total_views,
  count(distinct viewer_hash)::int as unique_views,
  max(created_at) as last_viewed_at
from post_views
group by post_id;

alter table posts enable row level security;
alter table post_views enable row level security;

create policy "Public read published posts"
  on posts for select
  using (
    status = 'published'
    or (auth.jwt() ->> 'email') = 'rmoreno.cesar@gmail.com'
  );

create policy "Author can create posts"
  on posts for insert
  with check (
    author_id = auth.uid()
    and (auth.jwt() ->> 'email') = 'rmoreno.cesar@gmail.com'
  );

create policy "Author can update posts"
  on posts for update
  using (
    author_id = auth.uid()
    and (auth.jwt() ->> 'email') = 'rmoreno.cesar@gmail.com'
  );

create policy "Author can delete posts"
  on posts for delete
  using (
    author_id = auth.uid()
    and (auth.jwt() ->> 'email') = 'rmoreno.cesar@gmail.com'
  );

create policy "Anyone can insert views for published posts"
  on post_views for insert
  with check (
    exists (
      select 1 from posts
      where posts.id = post_views.post_id
        and posts.status = 'published'
    )
  );

create policy "Author can read post views"
  on post_views for select
  using (
    exists (
      select 1 from posts
      where posts.id = post_views.post_id
        and posts.author_id = auth.uid()
        and (auth.jwt() ->> 'email') = 'rmoreno.cesar@gmail.com'
    )
  );
